services:
  # DATABASE_URL="postgresql://docker:docker@localhost:5432/plannerv4_dev"
  plannerv4-pg:
    image: bitnami/postgresql:latest
    container_name: plannerv4-pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=plannerv4_dev
    volumes:
      - plannerv4_postgres_data:/bitnami/postgresql
    networks:
      - plannerv4-net

  plannerv4_redis:
    image: redis:7-alpine
    container_name: plannerv4_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - plannerv4-net

volumes:
  plannerv4_postgres_data:

networks:
  plannerv4-net:
    driver: bridge

# docker compose -f compose.dev.yml up -d


